services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root  # <-- You must provide a value here
      MYSQL_DATABASE: blog_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: .  # Build context is current folder
    ports:
      - "3000:3000"
    volumes:
      - .:/app  # Mount current folder to /app inside the container
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql://root:root@db:3306/blog_db

volumes:
  db_data:
